// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	provider "github.com/user/qmd-go/internal/provider"
)

// Embedder is an autogenerated mock type for the Embedder type
type Embedder struct {
	mock.Mock
}

type Embedder_Expecter struct {
	mock *mock.Mock
}

func (_m *Embedder) EXPECT() *Embedder_Expecter {
	return &Embedder_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Embedder) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Embedder_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Embedder_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Embedder_Expecter) Close() *Embedder_Close_Call {
	return &Embedder_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Embedder_Close_Call) Run(run func()) *Embedder_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Embedder_Close_Call) Return(_a0 error) *Embedder_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Embedder_Close_Call) RunAndReturn(run func() error) *Embedder_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Dimensions provides a mock function with no fields
func (_m *Embedder) Dimensions() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dimensions")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Embedder_Dimensions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dimensions'
type Embedder_Dimensions_Call struct {
	*mock.Call
}

// Dimensions is a helper method to define mock.On call
func (_e *Embedder_Expecter) Dimensions() *Embedder_Dimensions_Call {
	return &Embedder_Dimensions_Call{Call: _e.mock.On("Dimensions")}
}

func (_c *Embedder_Dimensions_Call) Run(run func()) *Embedder_Dimensions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Embedder_Dimensions_Call) Return(_a0 int) *Embedder_Dimensions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Embedder_Dimensions_Call) RunAndReturn(run func() int) *Embedder_Dimensions_Call {
	_c.Call.Return(run)
	return _c
}

// Embed provides a mock function with given fields: ctx, texts, opts
func (_m *Embedder) Embed(ctx context.Context, texts []string, opts provider.EmbedOpts) ([][]float32, error) {
	ret := _m.Called(ctx, texts, opts)

	if len(ret) == 0 {
		panic("no return value specified for Embed")
	}

	var r0 [][]float32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, provider.EmbedOpts) ([][]float32, error)); ok {
		return rf(ctx, texts, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, provider.EmbedOpts) [][]float32); ok {
		r0 = rf(ctx, texts, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]float32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, provider.EmbedOpts) error); ok {
		r1 = rf(ctx, texts, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Embedder_Embed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Embed'
type Embedder_Embed_Call struct {
	*mock.Call
}

// Embed is a helper method to define mock.On call
//   - ctx context.Context
//   - texts []string
//   - opts provider.EmbedOpts
func (_e *Embedder_Expecter) Embed(ctx interface{}, texts interface{}, opts interface{}) *Embedder_Embed_Call {
	return &Embedder_Embed_Call{Call: _e.mock.On("Embed", ctx, texts, opts)}
}

func (_c *Embedder_Embed_Call) Run(run func(ctx context.Context, texts []string, opts provider.EmbedOpts)) *Embedder_Embed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(provider.EmbedOpts))
	})
	return _c
}

func (_c *Embedder_Embed_Call) Return(_a0 [][]float32, _a1 error) *Embedder_Embed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Embedder_Embed_Call) RunAndReturn(run func(context.Context, []string, provider.EmbedOpts) ([][]float32, error)) *Embedder_Embed_Call {
	_c.Call.Return(run)
	return _c
}

// NewEmbedder creates a new instance of Embedder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmbedder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Embedder {
	mock := &Embedder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
