// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	provider "github.com/user/qmd-go/internal/provider"
)

// Generator is an autogenerated mock type for the Generator type
type Generator struct {
	mock.Mock
}

type Generator_Expecter struct {
	mock *mock.Mock
}

func (_m *Generator) EXPECT() *Generator_Expecter {
	return &Generator_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Generator) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Generator_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Generator_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Generator_Expecter) Close() *Generator_Close_Call {
	return &Generator_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Generator_Close_Call) Run(run func()) *Generator_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Generator_Close_Call) Return(_a0 error) *Generator_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Generator_Close_Call) RunAndReturn(run func() error) *Generator_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Generate provides a mock function with given fields: ctx, messages, opts
func (_m *Generator) Generate(ctx context.Context, messages []provider.Message, opts provider.GenOpts) (string, error) {
	ret := _m.Called(ctx, messages, opts)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []provider.Message, provider.GenOpts) (string, error)); ok {
		return rf(ctx, messages, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []provider.Message, provider.GenOpts) string); ok {
		r0 = rf(ctx, messages, opts)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []provider.Message, provider.GenOpts) error); ok {
		r1 = rf(ctx, messages, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Generator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type Generator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - messages []provider.Message
//   - opts provider.GenOpts
func (_e *Generator_Expecter) Generate(ctx interface{}, messages interface{}, opts interface{}) *Generator_Generate_Call {
	return &Generator_Generate_Call{Call: _e.mock.On("Generate", ctx, messages, opts)}
}

func (_c *Generator_Generate_Call) Run(run func(ctx context.Context, messages []provider.Message, opts provider.GenOpts)) *Generator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]provider.Message), args[2].(provider.GenOpts))
	})
	return _c
}

func (_c *Generator_Generate_Call) Return(_a0 string, _a1 error) *Generator_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Generator_Generate_Call) RunAndReturn(run func(context.Context, []provider.Message, provider.GenOpts) (string, error)) *Generator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewGenerator creates a new instance of Generator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Generator {
	mock := &Generator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
