// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	provider "github.com/user/qmd-go/internal/provider"
)

// Reranker is an autogenerated mock type for the Reranker type
type Reranker struct {
	mock.Mock
}

type Reranker_Expecter struct {
	mock *mock.Mock
}

func (_m *Reranker) EXPECT() *Reranker_Expecter {
	return &Reranker_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Reranker) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reranker_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Reranker_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Reranker_Expecter) Close() *Reranker_Close_Call {
	return &Reranker_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Reranker_Close_Call) Run(run func()) *Reranker_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Reranker_Close_Call) Return(_a0 error) *Reranker_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Reranker_Close_Call) RunAndReturn(run func() error) *Reranker_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Rerank provides a mock function with given fields: ctx, query, docs, opts
func (_m *Reranker) Rerank(ctx context.Context, query string, docs []provider.RerankDoc, opts provider.RerankOpts) ([]provider.RerankResult, error) {
	ret := _m.Called(ctx, query, docs, opts)

	if len(ret) == 0 {
		panic("no return value specified for Rerank")
	}

	var r0 []provider.RerankResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []provider.RerankDoc, provider.RerankOpts) ([]provider.RerankResult, error)); ok {
		return rf(ctx, query, docs, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []provider.RerankDoc, provider.RerankOpts) []provider.RerankResult); ok {
		r0 = rf(ctx, query, docs, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]provider.RerankResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []provider.RerankDoc, provider.RerankOpts) error); ok {
		r1 = rf(ctx, query, docs, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reranker_Rerank_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rerank'
type Reranker_Rerank_Call struct {
	*mock.Call
}

// Rerank is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - docs []provider.RerankDoc
//   - opts provider.RerankOpts
func (_e *Reranker_Expecter) Rerank(ctx interface{}, query interface{}, docs interface{}, opts interface{}) *Reranker_Rerank_Call {
	return &Reranker_Rerank_Call{Call: _e.mock.On("Rerank", ctx, query, docs, opts)}
}

func (_c *Reranker_Rerank_Call) Run(run func(ctx context.Context, query string, docs []provider.RerankDoc, opts provider.RerankOpts)) *Reranker_Rerank_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]provider.RerankDoc), args[3].(provider.RerankOpts))
	})
	return _c
}

func (_c *Reranker_Rerank_Call) Return(_a0 []provider.RerankResult, _a1 error) *Reranker_Rerank_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Reranker_Rerank_Call) RunAndReturn(run func(context.Context, string, []provider.RerankDoc, provider.RerankOpts) ([]provider.RerankResult, error)) *Reranker_Rerank_Call {
	_c.Call.Return(run)
	return _c
}

// NewReranker creates a new instance of Reranker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReranker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reranker {
	mock := &Reranker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
